name: Build Windows Installer

# Workflow to build Windows installer for Dienstplan Splitter Virtual Printer
on:
  push:
    branches:
      - main
      - feature/virtual-printer
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Clean build directories
      run: |
        if exist "build" rd /s /q "build"
        if exist "dist" rd /s /q "dist"
        if exist "*.spec" del /f /q "*.spec"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir pyinstaller
        pip install --no-cache-dir pywin32

    - name: Create Version File
      run: |
        echo ${{ github.sha }} > version.txt
        echo ${{ github.ref }} >> version.txt

    - name: Build installer
      run: |
        pyinstaller --clean --onefile ^
          --add-data "version.txt;." ^
          --add-data "src/printer_service;printer_service" ^
          --add-data "src/core;core" ^
          --add-data "src/gui;gui" ^
          --icon=icon.png ^
          --name dienstplan_splitter_printer_setup ^
          --uac-admin ^
          src/manage_printer.py

    - name: Test installer
      run: |
        dir dist
        dist\dienstplan_splitter_printer_setup.exe status

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: dienstplan-splitter-printer-setup
        path: dist/dienstplan_splitter_printer_setup.exe 