name: Build Windows Executable

# Workflow to build Windows executable for Dienstplan Splitter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Clean build directories
      run: |
        if exist "build" rd /s /q "build"
        if exist "dist" rd /s /q "dist"
        if exist "*.spec" del /f /q "*.spec"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Build executable
      run: |
        pip install --no-cache-dir pyinstaller
        pyinstaller --clean --onefile --windowed dienstplan_splitter_gui.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dienstplan-splitter-${{ github.sha }}
        path: dist/ 