name: Build Windows Installer

# Workflow to build Windows installer for Dienstplan Splitter Virtual Printer
on:
  push:
    branches:
      - main
      - feature/virtual-printer
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Clean build directories
      shell: cmd
      run: |
        if exist "build" rd /s /q "build"
        if exist "dist" rd /s /q "dist"
        if exist "*.spec" del /f /q "*.spec"

    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir pyinstaller==6.1.0
        pip install --no-cache-dir pywin32==306
        pip install --no-cache-dir watchdog==3.0.0

    - name: Create Version File
      shell: cmd
      run: |
        echo %GITHUB_SHA% > version.txt
        echo %GITHUB_REF% >> version.txt

    - name: Build installer
      shell: cmd
      run: |
        pyinstaller --clean --onefile ^
          --add-data "version.txt;." ^
          --add-data "src/printer_service;printer_service" ^
          --add-data "src/core;core" ^
          --add-data "src/gui;gui" ^
          --icon=icon.png ^
          --name dienstplan_splitter_printer_setup ^
          --uac-admin ^
          src/manage_printer.py

    - name: Verify build output
      shell: cmd
      run: |
        dir dist
        if not exist "dist\dienstplan_splitter_printer_setup.exe" (
          echo Error: Installer not found in dist directory
          exit /b 1
        )

    - name: Upload installer as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dienstplan-splitter-printer-setup
        path: dist/dienstplan_splitter_printer_setup.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: DienstplanSplitter Virtual Printer ${{ github.ref_name }}
        draft: false
        prerelease: true
        files: |
          dist/dienstplan_splitter_printer_setup.exe
        body: |
          ## DienstplanSplitter Virtual Printer ${{ github.ref_name }}
          
          ### Installation
          1. Installer herunterladen (`dienstplan_splitter_printer_setup.exe`)
          2. Als Administrator ausführen
          3. Der virtuelle Drucker wird automatisch installiert
          
          ### Deinstallation
          1. Installer erneut als Administrator ausführen
          2. `uninstall` auswählen 